default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

staging:
  <<: *default
  database: postgres
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: gymapp_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: gymapp_test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV["HEROKU_POSTGRESQL_IVORY_URL"] %>
  database: gymapp_production