name: Deploy to ECS Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: mersonff/gymapp:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Render new ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          container-name: gymapp
          image: ${{ env.DOCKER_IMAGE }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: gymapp-task-service-5bdc0bc5
          cluster: gymapp-staging
          wait-for-service-stability: true

      - name: Run DB Migrations
        run: |
          aws ecs run-task \
            --cluster gymapp-staging \
            --launch-type FARGATE \
            --task-definition gymapp-task \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-07dffe1bc73b9987,subnet-029e184535015303a,subnet-0059446f121f1ce9a,subnet-00e20fd0c9065a546,subnet-0e3ea32c2eb3f89a6,subnet-0f76bf7ca625050c8],securityGroups=[sg-031fe14d9ecfa95b5],assignPublicIp=ENABLED}" \
            --overrides '{"containerOverrides":[{"name":"gymapp","command":["bundle","exec","rails","db:migrate"]}]}'
