name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  PROJECT_ID: gymapp-staging-1755293302
  SERVICE_NAME: gymapp
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: gymapp-staging-1755293302
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars RAILS_ENV=staging \
          --set-secrets DB_HOST=DB_HOST:latest \
          --set-secrets DB_USERNAME=DB_USERNAME:latest \
          --set-secrets DB_PASSWORD=DB_PASSWORD:latest \
          --set-secrets SECRET_KEY_BASE=SECRET_KEY_BASE:latest \
          --memory 1Gi \
          --cpu 1 \
          --port 3000

    - name: Run DB Migrations
      run: |
        gcloud run jobs create gymapp-migrate \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --region $REGION \
          --set-env-vars RAILS_ENV=staging \
          --set-secrets DB_HOST=DB_HOST:latest \
          --set-secrets DB_USERNAME=DB_USERNAME:latest \
          --set-secrets DB_PASSWORD=DB_PASSWORD:latest \
          --set-secrets SECRET_KEY_BASE=SECRET_KEY_BASE:latest \
          --command bundle \
          --args exec,rails,db:migrate \
          --replace || true
        
        gcloud run jobs execute gymapp-migrate --region $REGION --wait
